UKBCog = readtable('UKB_cogtests11.csv');
GetNames = UKBCog.Properties.VariableNames;
GetNames = GetNames(2:end-1);
GetNames{11} = 'Variance Explained';
UKBCog.cog_pairedAss_log = exp(UKBCog.cog_pairedAss_log)-1;
UKBCog = UKBCog(~(UKBCog.cog_numeric_memory==-1),:);
UKBCog = UKBCog.Variables;
numMiss = sum(isnan(UKBCog),2)<7;
UKBExclusion = readmatrix('UKB_exclusions_neuro.csv');
UKBCovar = readmatrix('UKBiobank_variables.csv');
nonNA = UKBCovar(sum(isnan(UKBCovar),2)==0,1);
CogtoCovar = ismember(UKBCog(:,1),UKBCovar(:,1)) & ismember(UKBCog(:,1),nonNA) & ~ismember(UKBCog(:,1),UKBExclusion);
CovartoCog = ismember(UKBCovar(:,1),UKBCog(:,1)) & ismember(UKBCovar(:,1),nonNA) & ~ismember(UKBCovar(:,1),UKBExclusion);
Index = find(CovartoCog == 1);
MRIcovars = UKBCovar(CovartoCog,4) == unique(UKBCovar(CovartoCog,4))';
additionalRemoval = ~(MRIcovars(:,4) == 1);
MRIcovars = [MRIcovars(:,1:3) UKBCovar(CovartoCog,5:7)];
DemoCovars = UKBCovar(CovartoCog,[2 3 11 14:16 18]);
AllCovars = [DemoCovars MRIcovars];
AllCovars = AllCovars(additionalRemoval,:);
UKBCog = UKBCog(CogtoCovar,:);
UKBCog = UKBCog(additionalRemoval,:);
Cog = UKBCog(:,2:end-1);
[lowApprox, PCA_score] = LRAMissing(Cog,2);
g_factor = -normalize(PCA_score);
UKBCog = [UKBCog(:,1:end-1) g_factor];
CovartoCog = zeros(37284,1);
CovartoCog(Index(additionalRemoval)) = 1;
CovartoCog = logical(CovartoCog);
Loadings = corr(Cog,g_factor,'Rows','pairwise');
Loadings = [Loadings;mean(Loadings.^2)];
g_factor_loading = array2table(Loadings);
g_factor_loading.Properties.RowNames = GetNames;
Covariates = array2table(AllCovars(:, [1 2 8:13]));
Covariates.Properties.VariableNames = ["Age", "Sex", "MRI_site1", "MRI_site2", "MRI_site3", "MRI_headpos_x", "MRI_headpos_y", "MRI_headpos_z"];
brain_var_array = AllCovars(:, [4 6 7]);
atrophy = AllCovars(:,5) - AllCovars(:,4);
atrophy_icv_corrected = fitlm(AllCovars(:,5),atrophy).Residuals.Standardized;
BrainVariables = array2table([brain_var_array atrophy_icv_corrected]);
BrainVariables.Properties.VariableNames = ["TBV", "GMV", "WMV", "Atrophy_{ICV corrected}"];
save("UKB_preprocessed_tabular_data.mat", "g_factor_loading", "Covariates", "g_factor", "CovartoCog");